# Generated by Django 5.2.7 on 2025-11-02 22:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sport_type', models.CharField(choices=[('gym', 'Gym'), ('rink', 'Ice Rink'), ('stadium', 'Stadium'), ('pool', 'Swimming Pool'), ('court', 'Sports Court'), ('other', 'Other')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
    ]
