# Generated by Django 5.2.7 on 2025-12-08 22:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_created_at_facility_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityzone',
            old_name='polygon',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='facilityzone',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='facilityzone',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='facilityzone',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sport_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facility',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from an external API such as Overpass/OSM.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='external_source',
            field=models.CharField(blank=True, help_text='Name of the external data source.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='source',
            field=models.CharField(blank=True, default='osm', help_text='Where this facility came from (e.g. osm, manual).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sport_type',
            field=models.CharField(choices=[('gym', 'Gym'), ('rink', 'Ice Rink'), ('stadium', 'Stadium'), ('pool', 'Swimming Pool'), ('court', 'Court'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='facilityzone',
            name='zone_type',
            field=models.CharField(choices=[('city', 'City'), ('district', 'District'), ('safety', 'Safety Zone'), ('coverage', 'Coverage Area')], default='coverage', max_length=50),
        ),
    ]
